-- Portfolio Items from pyramedia-portfolio.json
-- Generated automatically

TRUNCATE TABLE portfolio_items;

INSERT INTO portfolio_items (title, client, category, description, image, services, duration, featured, order_index) 
VALUES ('الهوية البصرية للأرشيف الوطني', 'الأرشيف الوطني - الإمارات', 'Branding', 'حوّلنا هوية الأرشيف الوطني الرقمية بتصميم يعكس التراث الإماراتي العريق مع لمسة عصرية. النتيجة: زيادة 250% في التفاعل الرقمي و 180% في الزيارات خلال 3 أشهر، مع تحسين الوعي بالعلامة التجارية بنسبة 320%.', 'https://via.placeholder.com/800x600/1a1a1a/d4af37?text=National+Archives', 'Branding, Identity Design, Government', '6 أشهر', 0, 1);
INSERT INTO portfolio_items (title, client, category, description, image, services, duration, featured, order_index) 
VALUES ('حملة مصرف الإمارات الرقمية', 'مصرف الإمارات الصناعي', 'Marketing', 'أطلقنا حملة تسويقية متكاملة لمصرف الإمارات الصناعي عبر جميع القنوات الرقمية. حققنا 450% زيادة في طلبات القروض و 280% نمو في فتح الحسابات الجديدة، مع ROI بلغ 520% خلال ربع واحد فقط.', 'https://via.placeholder.com/800x600/1a1a1a/d4af37?text=Emirates+Bank', 'Digital Marketing, Banking, Campaign', '4 أشهر', 0, 2);
INSERT INTO portfolio_items (title, client, category, description, image, services, duration, featured, order_index) 
VALUES ('تطبيق Awqaf Foundation', 'Awqaf Foundation', 'App Design', 'صممنا تطبيق جوال متكامل لمؤسسة الأوقاف بواجهة سهلة ومريحة. التطبيق حقق 150,000+ تحميل في أول 3 أشهر، مع تقييم 4.8/5 نجوم و 65% معدل استخدام يومي نشط.', 'https://via.placeholder.com/800x600/1a1a1a/d4af37?text=Awqaf+App', 'Mobile App, UI/UX, Islamic', '5 أشهر', 0, 3);
INSERT INTO portfolio_items (title, client, category, description, image, services, duration, featured, order_index) 
VALUES ('حملة KFC الرمضانية', 'KFC الإمارات', 'Social Media', 'أدرنا حملة رمضانية متكاملة لـ KFC عبر جميع منصات التواصل الاجتماعي. النتيجة: 8.5 مليون مشاهدة، 420% زيادة في التفاعل، و 180% نمو في المبيعات خلال شهر رمضان.', 'https://via.placeholder.com/800x600/1a1a1a/d4af37?text=KFC+Campaign', 'Social Media, F&B, Ramadan', 'شهر واحد', 0, 4);
INSERT INTO portfolio_items (title, client, category, description, image, services, duration, featured, order_index) 
VALUES ('استراتيجية noon الرقمية', 'noon', 'Digital Strategy', 'طوّرنا استراتيجية تسويق رقمي شاملة لمنصة noon. حققنا 3.2 مليون زيارة شهرية، 65% زيادة في معدل التحويل، و 290% نمو في قيمة الطلب المتوسط خلال 6 أشهر.', 'https://via.placeholder.com/800x600/1a1a1a/d4af37?text=noon+Strategy', 'E-commerce, Strategy, Growth', '6 أشهر', 0, 5);
INSERT INTO portfolio_items (title, client, category, description, image, services, duration, featured, order_index) 
VALUES ('حملة talabat الإعلانية', 'talabat', 'Advertising', 'أنشأنا حملة إعلانية متعددة القنوات لـ talabat عبر Google, Facebook, Instagram. النتيجة: 12 مليون مشاهدة، 520% زيادة في تحميل التطبيق، و 340% نمو في الطلبات الجديدة.', 'https://via.placeholder.com/800x600/1a1a1a/d4af37?text=talabat+Ads', 'Advertising, Food Delivery, Multi-channel', '3 أشهر', 0, 6);
INSERT INTO portfolio_items (title, client, category, description, image, services, duration, featured, order_index) 
VALUES ('تصميم موقع DAMAC', 'DAMAC Properties', 'Web Design', 'أعدنا تصميم موقع DAMAC Properties بتجربة مستخدم عصرية وسلسة. الموقع حقق 2.8 مليون زيارة شهرية، 85% تحسين في سرعة التحميل، و 450% زيادة في طلبات المعاينة.', 'https://via.placeholder.com/800x600/1a1a1a/d4af37?text=DAMAC+Website', 'Web Design, Real Estate, UX', '4 أشهر', 0, 7);
INSERT INTO portfolio_items (title, client, category, description, image, services, duration, featured, order_index) 
VALUES ('حملة Marina Mall التسويقية', 'Marina Mall', 'Marketing', 'نفّذنا حملة تسويقية متكاملة لـ Marina Mall خلال موسم الأعياد. حققنا 5.6 مليون مشاهدة، 380% زيادة في الزوار، و 520% نمو في المبيعات مقارنة بالعام السابق.', 'https://via.placeholder.com/800x600/1a1a1a/d4af37?text=Marina+Mall', 'Retail, Campaign, Seasonal', 'شهرين', 0, 8);
INSERT INTO portfolio_items (title, client, category, description, image, services, duration, featured, order_index) 
VALUES ('استراتيجية Rotana الرقمية', 'Rotana Hotels', 'Digital Marketing', 'طوّرنا استراتيجية تسويق رقمي شاملة لسلسلة فنادق روتانا. النتيجة: 1.9 مليون زيارة للموقع، 72% زيادة في الحجوزات المباشرة، و 280% نمو في برنامج الولاء.', 'https://via.placeholder.com/800x600/1a1a1a/d4af37?text=Rotana+Hotels', 'Hospitality, Digital Marketing, Loyalty', '8 أشهر', 0, 9);
INSERT INTO portfolio_items (title, client, category, description, image, services, duration, featured, order_index) 
VALUES ('تصميم هوية Salamh', 'Salamh', 'Branding', 'أنشأنا هوية بصرية متكاملة لعلامة Salamh من الصفر. الهوية حققت 95% معدل تذكر العلامة، 420% زيادة في الوعي بالعلامة التجارية، و 180% نمو في المبيعات خلال 6 أشهر.', 'https://via.placeholder.com/800x600/1a1a1a/d4af37?text=Salamh+Brand', 'Branding, Identity, Startup', '3 أشهر', 0, 10);
INSERT INTO portfolio_items (title, client, category, description, image, services, duration, featured, order_index) 
VALUES ('حملة Sharjah Electricity', 'هيئة كهرباء ومياه الشارقة', 'Government Campaign', 'أطلقنا حملة توعوية لترشيد استهلاك الكهرباء والمياه في الشارقة. الحملة وصلت لـ 4.2 مليون شخص، حققت 68% تفاعل، و ساهمت في تقليل الاستهلاك بنسبة 18% خلال 6 أشهر.', 'https://via.placeholder.com/800x600/1a1a1a/d4af37?text=SEWA+Campaign', 'Government, Awareness, Sustainability', '6 أشهر', 0, 11);
INSERT INTO portfolio_items (title, client, category, description, image, services, duration, featured, order_index) 
VALUES ('تصميم كتالوج وزارة الصحة', 'وزارة الصحة - الإمارات', 'Graphic Design', 'صممنا كتالوج رقمي تفاعلي لوزارة الصحة يعرض الخدمات والمبادرات الصحية. الكتالوج حقق 850,000+ مشاهدة، 82% معدل إكمال القراءة، و 340% زيادة في طلبات الخدمات.', 'https://via.placeholder.com/800x600/1a1a1a/d4af37?text=MOH+Catalog', 'Government, Catalog, Healthcare', 'شهرين', 0, 12);
INSERT INTO portfolio_items (title, client, category, description, image, services, duration, featured, order_index) 
VALUES ('حملة Abu Dhabi Business Hub', 'Abu Dhabi Business Hub', 'B2B Marketing', 'نفّذنا حملة تسويقية B2B لجذب الشركات العالمية لأبوظبي. حققنا 2,400+ lead مؤهل، 58% معدل تحويل، و 120+ شركة جديدة انضمت للمركز خلال سنة واحدة.', 'https://via.placeholder.com/800x600/1a1a1a/d4af37?text=ADBH+Campaign', 'B2B, Government, Lead Generation', 'سنة واحدة', 0, 13);
INSERT INTO portfolio_items (title, client, category, description, image, services, duration, featured, order_index) 
VALUES ('استراتيجية محتوى KFC', 'KFC الإمارات', 'Content Strategy', 'طوّرنا استراتيجية محتوى شاملة لـ KFC عبر جميع المنصات الرقمية. النتيجة: 15 مليون مشاهدة شهرياً، 520% زيادة في المتابعين، و 380% نمو في التفاعل.', 'https://via.placeholder.com/800x600/1a1a1a/d4af37?text=KFC+Content', 'Content, F&B, Social Media', 'سنة واحدة', 0, 14);
INSERT INTO portfolio_items (title, client, category, description, image, services, duration, featured, order_index) 
VALUES ('تصميم تطبيق noon', 'noon', 'App Design', 'أعدنا تصميم تجربة المستخدم لتطبيق noon بواجهة أكثر سهولة وسرعة. التطبيق حقق 4.7/5 تقييم، 85% تحسين في سرعة الشراء، و 420% زيادة في معدل إتمام الطلبات.', 'https://via.placeholder.com/800x600/1a1a1a/d4af37?text=noon+App', 'E-commerce, UX/UI, Mobile', '4 أشهر', 0, 15);
INSERT INTO portfolio_items (title, client, category, description, image, services, duration, featured, order_index) 
VALUES ('حملة talabat على Instagram', 'talabat', 'Social Media', 'أدرنا حملة Instagram متكاملة لـ talabat مع influencers ومحتوى تفاعلي. الحملة حققت 9.8 مليون مشاهدة، 680% زيادة في المتابعين، و 520% نمو في الطلبات من Instagram.', 'https://via.placeholder.com/800x600/1a1a1a/d4af37?text=talabat+IG', 'Instagram, Influencer, Food Delivery', '3 أشهر', 0, 16);
INSERT INTO portfolio_items (title, client, category, description, image, services, duration, featured, order_index) 
VALUES ('فيديو ترويجي DAMAC', 'DAMAC Properties', 'Video Production', 'أنتجنا فيديو ترويجي سينمائي لمشروع DAMAC الجديد بدبي. الفيديو حقق 6.5 مليون مشاهدة، 92% معدل إكمال المشاهدة، و 580% زيادة في حجوزات المعاينة.', 'https://via.placeholder.com/800x600/1a1a1a/d4af37?text=DAMAC+Video', 'Video, Real Estate, Production', 'شهرين', 0, 17);
INSERT INTO portfolio_items (title, client, category, description, image, services, duration, featured, order_index) 
VALUES ('حملة Marina Mall الموسمية', 'Marina Mall', 'Seasonal Campaign', 'نفّذنا حملة موسمية متكاملة لـ Marina Mall خلال Black Friday. حققنا 8.2 مليون مشاهدة، 520% زيادة في الزوار، و 780% نمو في المبيعات خلال 3 أيام فقط.', 'https://via.placeholder.com/800x600/1a1a1a/d4af37?text=Marina+BF', 'Retail, Black Friday, Campaign', 'شهر واحد', 0, 18);
INSERT INTO portfolio_items (title, client, category, description, image, services, duration, featured, order_index) 
VALUES ('برنامج ولاء Rotana', 'Rotana Hotels', 'Loyalty Program', 'طوّرنا برنامج ولاء رقمي متكامل لسلسلة فنادق روتانا. البرنامج جذب 180,000+ عضو في 6 أشهر، حقق 68% معدل نشاط، و 420% زيادة في الحجوزات المتكررة.', 'https://via.placeholder.com/800x600/1a1a1a/d4af37?text=Rotana+Loyalty', 'Hospitality, Loyalty, CRM', '6 أشهر', 0, 19);
INSERT INTO portfolio_items (title, client, category, description, image, services, duration, featured, order_index) 
VALUES ('تصميم packaging Salamh', 'Salamh', 'Packaging Design', 'صممنا عبوات منتجات Salamh بهوية بصرية جذابة ومميزة. التصميم حقق 88% معدل تفضيل من المستهلكين، 320% زيادة في المبيعات، و 95% معدل تذكر العلامة.', 'https://via.placeholder.com/800x600/1a1a1a/d4af37?text=Salamh+Pack', 'Packaging, Product Design, Branding', 'شهرين', 0, 20);
INSERT INTO portfolio_items (title, client, category, description, image, services, duration, featured, order_index) 
VALUES ('حملة توعية SEWA', 'هيئة كهرباء ومياه الشارقة', 'Awareness Campaign', 'أطلقنا حملة توعوية شاملة لترشيد استهلاك الطاقة في الشارقة. الحملة وصلت لـ 5.8 مليون شخص، حققت 75% معدل تذكر الرسالة، و ساهمت في تقليل الاستهلاك بنسبة 22%.', 'https://via.placeholder.com/800x600/1a1a1a/d4af37?text=SEWA+Aware', 'Government, Sustainability, Public Service', 'سنة واحدة', 0, 21);